variable "env" {}
variable "subnet_ids" {}
variable "allow_cidr_apps" {}
variable "vpc_id" {}
variable "component" {}
variable "app_port" {}
variable "desired_capacity" {}
variable "min_size" {}
variable "max_size" {}
variable "instances_type" {}
variable "allow_bastion_cidr" {}
variable "alb_dns_name" {}
variable "backend_app_listener" {}
variable "alb_arn" {}
variable "listener_priority" {}